name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  ftrackertest:
    runs-on: ubuntu-latest
    container: golang:1.22.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go test
        run: |
          go test -v ./...